# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      be-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/frontend-svelte"
    schedule:
      interval: "weekly"
    groups:
      fe-dependencies:
        patterns:
          - "*"
