services:
  app:
    build: .
    ports:
      - "8000:1234"
    environment:
      PORT: 1234
      FABX_DB_URL: jdbc:postgresql://postgres/postgres
      FABX_DB_USER: postgres
      FABX_DB_PASSWORD: postgrespassword
      # must be false when running multiple instances
      DATABASE_CACHING: true

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./tooling/prometheus.yml:/etc/prometheus/prometheus.yml