# Compose file for deployment
services:
  app:
    image: ghcr.io/fabxlabs/fabx:latest
    restart: unless-stopped
    ports:
      - "8080:1234"
    environment:
      PORT: 1234
      FABX_DB_URL: jdbc:postgresql://postgres/postgres
      FABX_DB_USER: postgres
      FABX_DB_PASSWORD: postgrespassword

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db:
