# Compose file for local development
services:
  app:
    build: .
    ports:
      - "8080:1234"
    environment:
      PORT: 1234
      FABX_DB_URL: jdbc:postgresql://postgres/postgres
      FABX_DB_USER: postgres
      FABX_DB_PASSWORD: postgrespassword
      # must be false when running multiple instances
      DATABASE_CACHING: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -h postgres
      retries: 5
      interval: 5s
      timeout: 5s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - pg-data:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./tooling/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  pg-data: