/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cloud.fabX.fabXaccess

import cloud.fabX.fabXaccess.user.model.User
import cloud.fabX.fabXaccess.user.model.newUserId

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    fun useDomain(): User {
        return User(newUserId(), "first", "last", "wiki", "phone", false, null)
    }
}

fun main() {
    println(App().greeting)
}
