<svelte:head>
	<title>fabX | Admin</title>
</svelte:head>

<div class="container relative max-w-screen-2xl mt-7">
	<h2 class="font-accent">Admin</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet dictum justo. Praesent felis ex, congue finibus eros vel, interdum varius erat. Aliquam erat volutpat. Nulla ac massa eu turpis sagittis vulputate eget vel erat. In et sapien vitae turpis pellentesque condimentum quis id massa. Vivamus dictum, libero vitae pretium gravida, sem lacus porta justo, at dictum arcu augue vitae enim. Fusce in nisi tempor, consectetur nulla a, porta odio. Donec molestie suscipit est, quis auctor velit consequat tincidunt.</p>
	<p>Nam et enim vitae justo rutrum faucibus eget sit amet diam. Duis tincidunt sapien turpis, at vehicula leo blandit eget. Aliquam pulvinar semper efficitur. Nam ut tempor enim. Integer vestibulum, lacus ac fringilla ultricies, odio velit cursus metus, et feugiat nunc nisl ut enim. Nam ut neque porta, scelerisque massa nec, dapibus nisi. Cras iaculis tellus sed mi varius volutpat. Morbi efficitur sapien eget faucibus ultricies. Fusce ornare dolor sed pellentesque mattis. Praesent vel arcu metus.</p>
	<p>Vestibulum hendrerit odio vel nibh sollicitudin accumsan. Aliquam suscipit sapien et ipsum porta imperdiet. Aliquam erat volutpat. Duis euismod massa ac placerat hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent rhoncus sit amet ex sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
	<p>Suspendisse efficitur feugiat diam vitae sodales. Integer placerat malesuada augue, eget varius turpis porta vulputate. Nulla lobortis mauris ut urna cursus, ut volutpat dui elementum. Vivamus in scelerisque erat. Nunc et mi at mi egestas ullamcorper. Nam euismod tincidunt ipsum quis vulputate. Sed tempor ligula nec libero gravida mattis. Duis eget feugiat diam, placerat fringilla elit. Etiam ultricies risus a tortor suscipit, efficitur iaculis ipsum sollicitudin. Quisque facilisis sem vel felis porttitor malesuada.</p>
	<p>Fusce sodales pretium orci. Nulla mollis arcu eu sapien bibendum, at aliquet quam fringilla. Etiam vulputate euismod erat in eleifend. Nunc sollicitudin, mauris quis semper mollis, sapien velit faucibus lectus, efficitur pharetra diam quam nec urna. Aliquam erat volutpat. Suspendisse magna massa, tincidunt vitae ullamcorper et, mattis vestibulum neque. Pellentesque ac pulvinar neque. Proin velit ipsum, hendrerit ac ornare a, dictum in nunc. Etiam id dolor odio. Maecenas blandit tristique augue mattis dignissim. Aliquam euismod justo magna, et faucibus nibh dapibus a.</p>
	<p>Aenean tempor accumsan dictum. Duis a ante varius, faucibus nibh nec, vehicula mauris. Pellentesque tempor purus malesuada auctor vehicula. Suspendisse egestas metus id ex egestas ornare. Pellentesque non enim a arcu varius semper nec a nibh. Ut volutpat arcu non elit blandit, vitae porttitor leo tristique. Donec eros risus, pretium eget finibus at, pellentesque quis neque. Pellentesque odio magna, euismod consectetur tincidunt sed, auctor sed odio. Proin nec accumsan lacus. Curabitur iaculis massa sed venenatis convallis.</p>
	<p>Nullam eleifend neque id erat malesuada dignissim. Aliquam condimentum nisl sit amet placerat feugiat. Phasellus fermentum, elit nec porttitor auctor, magna nisi condimentum felis, vel pretium felis elit venenatis nibh. Nunc consequat purus sed arcu finibus, nec pretium purus vestibulum. Donec nisl mauris, sollicitudin nec eleifend sed, commodo a augue. Ut turpis mi, venenatis at erat eget, egestas pharetra enim. Nam condimentum nulla risus, a rutrum purus mollis sed. Nulla varius varius lorem, mollis pulvinar ante eleifend vel. Proin nec dictum nulla, ut scelerisque mauris. Suspendisse in sem luctus, auctor dolor ut, vehicula quam. Nulla ullamcorper porttitor tincidunt.</p>
	<p>Mauris pellentesque lectus et eros tristique, non aliquet eros semper. Praesent quis dui vitae ligula sollicitudin ultricies. Integer turpis ante, iaculis sed lobortis eget, vehicula quis arcu. Donec vehicula condimentum mi in dictum. Nam pretium lacus a faucibus congue. Nullam volutpat lectus eu nisi feugiat suscipit. Mauris nec orci faucibus, posuere ipsum vitae, dictum tortor. Mauris pretium arcu lectus, ac posuere lectus aliquam a.</p>
	<p>Integer eu nibh id nisi tincidunt egestas a sed ipsum. Fusce porttitor euismod arcu, non sagittis massa aliquet at. Maecenas pulvinar erat ut feugiat tincidunt. Vestibulum nec ligula facilisis nibh consequat scelerisque ut a lacus. Nulla placerat ligula in tempor aliquet. Nam sit amet eleifend purus. Vivamus ac venenatis leo. Fusce semper dui nec tempus tincidunt. Duis congue ullamcorper nunc ac egestas. In scelerisque varius nunc sed ullamcorper. Aenean diam leo, ornare a facilisis vitae, tempus nec purus. Ut ut tincidunt justo.</p>
	<p>Aenean sed magna tempus, porttitor nisl eu, tempus dui. Fusce tempor sem et pellentesque eleifend. Mauris posuere sem sit amet risus sollicitudin, at condimentum eros fringilla. Donec blandit mauris et mauris varius, non sodales nulla finibus. Maecenas dapibus malesuada condimentum. Quisque nec euismod eros, quis blandit purus. Suspendisse vitae nibh lobortis, viverra urna eget, sagittis enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut venenatis malesuada urna ac imperdiet. Aliquam vitae venenatis erat. Mauris blandit turpis velit, nec molestie nisl ornare vitae. Curabitur ultricies feugiat hendrerit. Aliquam neque leo, tempus sit amet pellentesque ut, molestie et ipsum. Sed velit sapien, convallis eu metus ut, hendrerit varius arcu.</p>
	<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque sollicitudin sed quam vel bibendum. Ut vitae congue dolor. Nullam ornare tincidunt felis vel aliquet. Fusce accumsan odio nec viverra vulputate. Nullam rutrum imperdiet laoreet. Donec aliquam ultrices eros, eu maximus sem consectetur sed. Nulla rutrum consectetur eros non aliquam. In tincidunt ipsum quis tellus rhoncus, non aliquam leo porttitor. Mauris commodo est magna, ut euismod metus aliquam quis. Vestibulum facilisis urna non tortor auctor, non tempor neque rutrum. Cras fringilla sed ipsum eu dapibus.</p>
	<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc elementum eros tellus, dignissim fermentum augue tristique non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean malesuada posuere tristique. Etiam eget maximus magna. Vivamus posuere magna eget accumsan luctus. Phasellus tempus elit at lorem aliquam, sed blandit dolor pulvinar. Nullam in enim eros. Praesent euismod ante libero, pellentesque semper leo volutpat eget. Proin a mi at nibh varius facilisis ut consectetur sapien. Nullam pulvinar ligula et imperdiet viverra.</p>
	<p>Suspendisse malesuada, nunc a cursus pharetra, nunc justo interdum tortor, sit amet interdum ex elit et tortor. Suspendisse faucibus pellentesque dignissim. Praesent nec arcu nisi. Integer velit lectus, posuere id dui sit amet, tincidunt tristique lectus. Fusce lorem magna, tincidunt vitae arcu vitae, elementum ultricies lectus. Cras congue ex in sollicitudin tincidunt. Vivamus dignissim, odio vel accumsan interdum, ipsum magna cursus augue, ac lobortis elit mi vitae lorem. Proin bibendum vulputate rhoncus. Quisque nec turpis quis ligula lobortis placerat ut a tortor. Phasellus lacinia nunc at nunc scelerisque, vitae placerat dolor ullamcorper. Sed varius nibh vel finibus pulvinar. Nulla fringilla nibh a risus pulvinar, ut varius orci volutpat. Nulla lacus augue, vestibulum sit amet faucibus semper, ultrices id orci.</p>
	<p>Aliquam quis felis laoreet, pharetra lorem ac, elementum odio. Donec auctor posuere dignissim. Nullam mollis ornare enim nec dictum. Etiam id porttitor nunc. Mauris tempor elit eget enim malesuada interdum. Praesent ac quam elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec gravida bibendum odio, quis luctus diam elementum sollicitudin. Quisque lacinia sodales tellus, eu iaculis massa congue in. Mauris vel viverra massa.</p>
	<p>Morbi gravida eros vel suscipit condimentum. Maecenas massa urna, feugiat at ante nec, eleifend ultrices mi. Integer rhoncus et libero ut consequat. Duis vehicula, magna volutpat mollis volutpat, ex justo porttitor ante, eu tempus turpis urna sed tellus. Curabitur feugiat, nunc sagittis scelerisque maximus, leo mi vestibulum eros, et tincidunt sem mauris sit amet dolor. Sed maximus tempus nulla, quis consectetur augue ullamcorper iaculis. Integer vitae arcu cursus leo placerat aliquet vel interdum massa. Donec rutrum nisi a quam tempor mattis. Duis sollicitudin fermentum erat, quis volutpat orci tempor ac. Curabitur tortor est, accumsan quis venenatis eget, laoreet in orci. Pellentesque nec velit fermentum lectus aliquam commodo quis at libero. Praesent non accumsan felis. Proin ac ullamcorper massa, et commodo ligula.</p>
	<p>Cras malesuada ac est rutrum viverra. Sed vel lorem dapibus, tincidunt ligula sed, faucibus velit. Fusce egestas, sapien at dapibus feugiat, dolor risus tempor leo, nec consequat ligula nibh vel erat. Suspendisse commodo ultricies mi, vitae pulvinar urna cursus non. Aenean id odio mauris. Suspendisse condimentum tempus neque a faucibus. Aliquam vel neque euismod velit dapibus finibus vitae in arcu. Duis id dapibus ligula. In dictum fermentum tellus, at ultrices enim mollis vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer dui urna, tempor sit amet interdum ut, pellentesque at sapien. Quisque sed velit turpis. Donec elementum ante ac hendrerit sagittis. Nullam tellus arcu, gravida sodales pharetra vitae, efficitur eu nunc. Pellentesque et quam vel lectus aliquam tristique mollis porttitor nisi.</p>
	<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam at lacinia massa, eget euismod massa. Cras fermentum nec purus eget dapibus. Nunc semper leo at ligula tincidunt, eget ornare quam euismod. Praesent suscipit imperdiet nulla sed lobortis. Vivamus fringilla viverra tortor, nec semper elit vestibulum nec. Praesent in condimentum enim. Duis varius metus magna, tempor bibendum nibh fermentum ac. In eu mi neque. Duis eu consequat mi, vel venenatis turpis. Nam posuere, erat ac tincidunt auctor, dolor nunc volutpat turpis, ut commodo felis nibh et est.</p>
	<p>Integer et nunc lorem. Donec consectetur molestie eros, ac eleifend arcu rutrum ut. Vestibulum id eros ut lacus commodo finibus. Ut convallis fermentum dolor, a facilisis leo maximus et. Nunc purus dolor, gravida a nisi a, ullamcorper iaculis massa. Nulla vitae vestibulum elit. Praesent quis feugiat ex. Mauris scelerisque efficitur magna, sed fermentum arcu sagittis sed. Nullam egestas risus diam, ac blandit ligula tincidunt id.</p>
	<p>Curabitur est nulla, lacinia fermentum nisi a, scelerisque vestibulum dolor. Curabitur convallis augue id risus mattis hendrerit. Sed scelerisque eros odio. Vivamus tincidunt odio vitae dictum euismod. Nam fermentum eros nec turpis luctus lacinia vel fringilla enim. Duis orci est, imperdiet nec tincidunt vitae, suscipit ac turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
	<p>Nullam luctus mauris ac erat volutpat vehicula. Aliquam et purus turpis. Nullam ac nisl eros. Nam fermentum viverra mattis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas quis convallis sem, et ultrices metus. In hac habitasse platea dictumst. Quisque laoreet mauris sed ipsum ultrices, nec semper turpis suscipit. Aliquam erat volutpat. Proin tempor tincidunt dictum. Nullam purus nunc, tincidunt vitae pharetra vitae, egestas quis mauris. In purus augue, iaculis sed vulputate eu, tincidunt sed sem. Pellentesque diam ligula, dignissim quis mattis eget, semper in metus. Cras tincidunt id dui quis auctor. Mauris lacinia ultricies sapien.</p>
</div>
