global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['host.containers.internal:8080']
    basic_auth:
      username: metrics
      password: supersecretmetricspassword
