name: CI

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: fabx

jobs:
  build:
    name: Build & Publish

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      with:
        search_commit_body: true
        bump_each_commit: true

    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Backend
      run: ./gradlew classes -x npmInstall -x npmBuild

    - name: Test Backend
      run: ./gradlew check -x npmInstall -x npmBuild

    - name: Build Fat JAR
      run: ./gradlew stage
      env:
        FABX_VERSION: ${{ steps.version.outputs.version }}

    - name: Build Docker Image
      run: docker build --tag $IMAGE_NAME .

    - name: Log in to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION