name: CI

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: fabx

jobs:
  build:
    name: Build & Publish

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
        search_commit_body: true
        bump_each_commit: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.11.0

    - name: Build Backend
      run: ./gradlew classes -x npmInstall -x npmBuild

    - name: Test Backend
      run: ./gradlew check -x npmInstall -x npmBuild

    - name: Build Fat JAR
      run: ./gradlew stage
      env:
        FABX_VERSION: ${{ steps.version.outputs.version }}

    - name: Log in to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: 'linux/amd64,linux/arm64'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lowercase repo owner name
      run: |
        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

    - name: Build and push container image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:latest
          ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
        platforms: linux/amd64,linux/arm64
