name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Backend

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Backend
      run: ./gradlew classes -x npmInstall -x npmBuild

    - name: Test Backend
      run: ./gradlew check -x npmInstall -x npmBuild

    - name: Build Fat JAR
      run: ./gradlew stage
    # TODO publish Docker image to GitHub Packages