name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: ./gradlew classes
    
    - name: Test
      run: ./gradlew check
