name: HK-DEV

concurrency: hk-dev

on:
  workflow_dispatch:

env:
  IMAGE_NAME: fabx
  VERSION: latest
  HK_NAME: fabx-dev

jobs:
  deploy:
    name: Deploy to DEV

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Image from Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION
          docker pull $IMAGE_ID

      - name: Log in to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fabx-dev"
          heroku_email: "simon.schaeffner@googlemail.com"
          region: "eu"
          justlogin: true

      - name: Create Heroku App
        run: heroku create $HK_NAME || true

      - name: Create Postgres Addon
        run: (heroku addons:create heroku-postgresql:hobby-dev --as=DATABASE -a $HK_NAME && heroku ps:restart -a $HK_NAME) || true

      - name: Push to Heroku Registry
        run: |
          docker tag $IMAGE_ID registry.heroku.com/$HK_NAME/web
          docker push registry.heroku.com/$HK_NAME/web

      - name: Release
        run: heroku container:release web -a $HK_NAME


