name: HK-DEV

concurrency: hk-dev

on:
  #push:
  #  branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fabx-dev"
          heroku_email: "simon.schaeffner@googlemail.com"
          region: "eu"

      - name: create postgres
        run: heroku addons:create heroku-postgresql:hobby-dev --as=DATABASE -a fabx-dev || true
