name: HK-DEV

concurrency: hk-dev

on:
  workflow_dispatch:

env:
  IMAGE_NAME: fabx
  VERSION: latest
  HK_NAME: fabx-dev
  HK_REGION: eu
  JWT_ISSUER: https://fabx-dev.herokuapp.com/
  JWT_AUDIENCE: https://fabx-dev.herokuapp.com/
  WEBAUTHN_ORIGIN: https://fabx-dev.herokuapp.com
  WEBAUTHN_RP_ID: fabx-dev.herokuapp.com
  WEBAUTHN_RP_NAME: "fabX DEV"

jobs:
  deploy:
    name: Deploy to DEV

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Log in to GitHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: $HK_NAME
          heroku_email: "simon.schaeffner@googlemail.com"
          region: "eu"
          justlogin: true

      - name: Log in to Heroku Registry
        run: heroku container:login

      - name: Create Heroku App
        run: heroku create --addons=heroku-postgresql:hobby-dev --region=$HK_REGION --no-remote $HK_NAME || true

      - name: Set Environment Variables
        run: |
          heroku config:set -a $HK_NAME JWT_ISSUER=$JWT_ISSUER
          heroku config:set -a $HK_NAME JWT_AUDIENCE=$JWT_AUDIENCE
          heroku config:set -a $HK_NAME JWT_HMAC256_SECRET=${{ secrets.JWT_HMAC256_SECRET }}
          heroku config:set -a $HK_NAME WEBAUTHN_ORIGIN=$WEBAUTHN_ORIGIN
          heroku config:set -a $HK_NAME WEBAUTHN_RP_ID=$WEBAUTHN_RP_ID
          heroku config:set -a $HK_NAME WEBAUTHN_RP_NAME=$WEBAUTHN_RP_NAME

      - name: Determine Image ID
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION
          echo "image_id=$IMAGE_ID" >> $GITHUB_ENV

      - name: Pull Image from Registry
        run: docker pull ${{ env.image_id }}

      - name: Push Image to Heroku Registry
        run: |
          docker tag ${{ env.image_id }} registry.heroku.com/$HK_NAME/web
          docker push registry.heroku.com/$HK_NAME/web

      - name: Release
        run: heroku container:release web -a $HK_NAME


