name: Linting

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-svelte
    steps:
    - uses: actions/checkout@v4   
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend-svelte/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint